# Generated by Django 5.0.6 on 2024-06-27 06:48

from django.db import migrations


def populate_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    Tag.objects.create(name='Experienced')
    Tag.objects.create(name='Newbie')


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_tags),
    ]
