# Generated by Django 5.0.6 on 2024-06-27 06:47

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    Category.objects.create(name='Full-time')
    Category.objects.create(name='Part-time')
    Category.objects.create(name='Intern')


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
