# Generated by Django 5.0.6 on 2024-06-27 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='DefaultFirstName', max_length=100)),
                ('last_name', models.CharField(default='DefaultLastName', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(default='NotSpecified', max_length=10)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('address', models.CharField(default='DefaultAddress', max_length=255)),
                ('country', models.CharField(default='DefaultCountry', max_length=100)),
                ('province', models.CharField(default='DefaultProvince', max_length=100)),
                ('city', models.CharField(default='DefaultCity', max_length=100)),
                ('area_code', models.CharField(default='0000', max_length=10)),
                ('categories', models.ManyToManyField(to='categories.category')),
                ('tags', models.ManyToManyField(to='tags.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
